# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DPU/DPU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPU || ORIG_REF_NAME==DPU} -quiet] -quiet

# IP: bd/DPU/ip/DPU_processing_system7_0_0/DPU_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPU_processing_system7_0_0 || ORIG_REF_NAME==DPU_processing_system7_0_0} -quiet] -quiet

# IP: bd/DPU/ip/DPU_dpu_conv_top_0_0/DPU_dpu_conv_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPU_dpu_conv_top_0_0 || ORIG_REF_NAME==DPU_dpu_conv_top_0_0} -quiet] -quiet

# IP: bd/DPU/ip/DPU_axi_smc_0/DPU_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPU_axi_smc_0 || ORIG_REF_NAME==DPU_axi_smc_0} -quiet] -quiet

# IP: bd/DPU/ip/DPU_rst_ps7_0_50M_0/DPU_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DPU_rst_ps7_0_50M_0 || ORIG_REF_NAME==DPU_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/DPU_ooc.xdc
