# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.srcs/sources_1/bd/DPU/ip/DPU_axi_smc_0/DPU_axi_smc_0.xci
# IP: The module: 'DPU_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/bd_1c95.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_1/bd_1c95_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_2/bd_1c95_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_3/bd_1c95_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_4/bd_1c95_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_5/bd_1c95_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_6/bd_1c95_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_7/bd_1c95_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_8/bd_1c95_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_9/bd_1c95_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_10/bd_1c95_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_11/bd_1c95_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_12/bd_1c95_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_13/bd_1c95_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_14/bd_1c95_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_15/bd_1c95_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_16/bd_1c95_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_17/bd_1c95_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_18/bd_1c95_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_19/bd_1c95_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_20/bd_1c95_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_21/bd_1c95_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_22/bd_1c95_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_23/bd_1c95_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_24/bd_1c95_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_25/bd_1c95_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_26/bd_1c95_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_27/bd_1c95_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_28/bd_1c95_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_29/bd_1c95_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_30/bd_1c95_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_31/bd_1c95_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_32/bd_1c95_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_33/bd_1c95_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_34/bd_1c95_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_35/bd_1c95_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_36/bd_1c95_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_37/bd_1c95_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_38/bd_1c95_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_39/bd_1c95_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_1/bd_1c95_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_2/bd_1c95_arinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_3/bd_1c95_rinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_4/bd_1c95_awinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_5/bd_1c95_winsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_6/bd_1c95_binsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_7/bd_1c95_aroutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_8/bd_1c95_routsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_9/bd_1c95_awoutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_10/bd_1c95_woutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_11/bd_1c95_boutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_12/bd_1c95_arni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_13/bd_1c95_rni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_14/bd_1c95_awni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_15/bd_1c95_wni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_16/bd_1c95_bni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_20/bd_1c95_s00a2s_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_21/bd_1c95_sarn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_22/bd_1c95_srn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_23/bd_1c95_sawn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_24/bd_1c95_swn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_25/bd_1c95_sbn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_26/bd_1c95_m00s2a_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_27/bd_1c95_m00arn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_28/bd_1c95_m00rn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_29/bd_1c95_m00awn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_30/bd_1c95_m00wn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_31/bd_1c95_m00bn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_33/bd_1c95_m01s2a_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_34/bd_1c95_m01arn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_35/bd_1c95_m01rn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_36/bd_1c95_m01awn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_37/bd_1c95_m01wn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_38/bd_1c95_m01bn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.srcs/sources_1/bd/DPU/ip/DPU_axi_smc_0/DPU_axi_smc_0.xci
# IP: The module: 'DPU_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/bd_1c95.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_1/bd_1c95_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_2/bd_1c95_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_3/bd_1c95_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_4/bd_1c95_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_5/bd_1c95_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_6/bd_1c95_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_7/bd_1c95_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_8/bd_1c95_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_9/bd_1c95_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_10/bd_1c95_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_11/bd_1c95_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_12/bd_1c95_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_13/bd_1c95_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_14/bd_1c95_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_15/bd_1c95_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_16/bd_1c95_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_17/bd_1c95_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_18/bd_1c95_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_19/bd_1c95_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_20/bd_1c95_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_21/bd_1c95_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_22/bd_1c95_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_23/bd_1c95_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_24/bd_1c95_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_25/bd_1c95_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_26/bd_1c95_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_27/bd_1c95_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_28/bd_1c95_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_29/bd_1c95_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_30/bd_1c95_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_31/bd_1c95_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_32/bd_1c95_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_33/bd_1c95_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_34/bd_1c95_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_35/bd_1c95_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_36/bd_1c95_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_37/bd_1c95_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_38/bd_1c95_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_39/bd_1c95_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_1/bd_1c95_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_2/bd_1c95_arinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_3/bd_1c95_rinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_4/bd_1c95_awinsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_5/bd_1c95_winsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_6/bd_1c95_binsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_7/bd_1c95_aroutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_8/bd_1c95_routsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_9/bd_1c95_awoutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_10/bd_1c95_woutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_11/bd_1c95_boutsw_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_12/bd_1c95_arni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_13/bd_1c95_rni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_14/bd_1c95_awni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_15/bd_1c95_wni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_16/bd_1c95_bni_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_20/bd_1c95_s00a2s_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_21/bd_1c95_sarn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_22/bd_1c95_srn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_23/bd_1c95_sawn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_24/bd_1c95_swn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_25/bd_1c95_sbn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_26/bd_1c95_m00s2a_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_27/bd_1c95_m00arn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_28/bd_1c95_m00rn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_29/bd_1c95_m00awn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_30/bd_1c95_m00wn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_31/bd_1c95_m00bn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_33/bd_1c95_m01s2a_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_34/bd_1c95_m01arn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_35/bd_1c95_m01rn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_36/bd_1c95_m01awn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_37/bd_1c95_m01wn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/bd_0/ip/ip_38/bd_1c95_m01bn_0_ooc.xdc

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/project/DPU_Project_vivado/DPU_vivado/DPU_vivado.gen/sources_1/bd/DPU/ip/DPU_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
